### ISSUE TITLE
Habitation_RAW_Shapefile/Punjab.zip is broken

### ISSUE THREAD

**Issue by planemad** [justinelliotmeyers/India_Official_Data_2022#1]
Contains empty shapefile

**Comment by justinelliotmeyers** [comment]
![in_site](https://user-images.githubusercontent.com/5324316/155320820-e12cb3be-8661-41ca-b8b1-612b551a3b18.png)
As soon as site works, I will re-download and upload.

**Comment by justinelliotmeyers** [comment]
@planemad confirmed with other colleagues their identical download for this file is the same (empty).

**Comment by kabilsharma** [comment]
Punjab Habitation is giving a Line Data instead of Point data.

**Comment by justinelliotmeyers** [comment]
@kabilsharma thanks for the information. We brought this to the agency's attention. They are looking into it and a resolution. I'll ask when we can expect a stable output. Have you noticed anything else?

Really appreciate your time and help!
Justin

**Comment by kabilsharma** [comment]
All habitation data has projection issue. It has SRID 6325 when we try to reproject , reassign projection doesnt work. May be it doesnt support 4326 projection.

**Comment by justinelliotmeyers** [comment]
![image](https://user-images.githubusercontent.com/5324316/155993945-79a38b36-e4da-45e9-ab23-05f1ad6b8b02.png)
contacted main data person this morning. Will see what I can do.

**Comment by justinelliotmeyers** [comment]
![punjab_update](https://user-images.githubusercontent.com/5324316/157888252-ce7be2db-a242-4264-9261-786ce978db6a.png)
updated file.
