### ISSUE TITLE
Proposals_RAW_Shapefile

### ISSUE THREAD

**Issue by simon-reyburn** [justinelliotmeyers/India_Official_Data_2022#5]
Hi Justin,
Thanks for sharing the PMGSY Data. Do you know what exactly the "Proposals" cover? Proposals for PMGSY-III road program? Can't find much info on the official download platform. I am looking for a shapefile of roads built as part of former programs (PMGSY I and II).
Thanks,
Simon

**Comment by justinelliotmeyers** [comment]
Simon,
I'll try to find out and get back to you.
Cheers,
Justin

**Comment by simon-reyburn** [comment]
Much appreciated. Thanks

**Comment by justinelliotmeyers** [comment]
Simon,
I was told they are 'not yet built roads as of dataset publishing time'

There is a telegram group for OpenStreetMap India where they are super responsive and helpful to all things India geospatial related. If you have future questions, they would probably be a great resource. Good luck in what you are developing. If you need anything in the future just reach out.
Cheers
